name: 'Candid, NC'
favicon: null
layout_spectrum: 0.8263089498504996
typography_spectrum: 0.3255055923946202
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.0011413961183279753
  lightness: 0.4481375499162823
  saturation: 0.8811412765644491
  rhythmicContrast: 0.9698989710304886
purpose: []
